import { NCGeneralSettingsT } from './nc_types'

export const NC_DEFAULT_SETTINGS: Required<NCGeneralSettingsT> = {

    classSuffixes: [],

    enumSuffixes: ['Enum'],
    interfacePrefixes: ['I'],
    typeSuffixes: ['T'],
    typeSuffixesGenerics: ['T'],

    /* eslint-disable @typescript-eslint/naming-convention */
    arraySuffixesUC: ['S', 'ARRAY', 'LIST'],
    arraySuffixesLC: ['s', 'Array', 'List'],
    booleanPrefixesUC: ['IS', 'ENABLE', 'REQUIRE', 'FORCE', 'DONT', 'USE'],
    booleanPrefixesLC: ['are', 'can', 'did', 'disable', 'dont', 'enable', 'force', 'has', 'have', 'is', 'match', 'must', 'require', 'should', 'use', 'was', 'will'],
    /* eslint-enable @typescript-eslint/naming-convention */

    functionPrefixes: [
        'add',
        'alert',
        'are',
        'ask',
        'begin',
        'bind',
        'bond',
        'break',
        'build',
        'cancel',
        'change',
        'check',
        'close',
        'compute',
        'concat',
        'conclude',
        'connect',
        'create',
        'debug',
        'delete',
        'derive',
        'did',
        'didnt',
        'direct',
        'disable',
        'disconnect',
        'divide',
        'do',
        'does',
        'doesnt',
        'dont',
        'double',
        'drive',
        'enable',
        'engage',
        'erase',
        'execute',
        'explode',
        'extract',
        'find',
        'finish',
        'fix',
        'get',
        'give',
        'grab',
        'grant',
        'handle',
        'has',
        'have',
        'hide',
        'initialize',
        'install',
        'is',
        'list',
        'lock',
        'make',
        'match',
        'merge',
        'mix',
        'mount',
        'move',
        'multiply',
        'notify',
        'onChange',
        'onClick',
        'onClose',
        'onCreate',
        'onDelete',
        'onError',
        'onFinish',
        'onUpdate',
        'open',
        'parse',
        'pick',
        'place',
        'preValidate',
        'print',
        'pull',
        'put',
        'quit',
        'raise',
        'redirect',
        'redo',
        'register',
        'remove',
        'reset',
        'revert',
        'run',
        'save',
        'search',
        'select',
        'sell',
        'send',
        'set',
        'should',
        'show',
        'solve',
        'sort',
        'split',
        'start',
        'strip',
        'subscribe',
        'subtract',
        'sum',
        'take',
        'throw',
        'to',
        'transform',
        'treat',
        'truncate',
        'unbind',
        'uncheck',
        'undo',
        'uninstall',
        'unmount',
        'unregister',
        'unsubscribe',
        'upsert',
        'validate',
        'verify',
        'warn',
        'was',
        'wasnt',
        'will',
        'witch',
        'write',
        'zero',
    ],
}
