import { ncGeneralSettingsT } from './ncTypes'

export const NC_DEFAULT_SETTINGS: Required<ncGeneralSettingsT> = {

    classSuffixes: [],

    enumSuffixes: ['Enum'],
    interfacePrefixes: ['I'],
    typeSuffixes: ['T'],
    typeSuffixesGenerics: ['T'],

    /* eslint-disable @typescript-eslint/naming-convention */
    arraySuffixesUC: ['S', 'ARRAY', 'LIST'],
    arraySuffixesLC: ['s', 'Array', 'List'],
    booleanPrefixesUC: ['IS', 'ENABLE', 'REQUIRE', 'FORCE', 'DONT', 'USE'],
    booleanPrefixesLC: ['are', 'can', 'did', 'dont', 'enable', 'force', 'has', 'have', 'is', 'must', 'require', 'should', 'use', 'will'],
    /* eslint-enable @typescript-eslint/naming-convention */

    functionPrefixes: [
        'add',
        'are',
        'bond',
        'build',
        'check',
        'concat',
        'create',
        'debug',
        'delete',
        'disable',
        'divide',
        'does',
        'enable',
        'execute',
        'find',
        'finish',
        'fix',
        'get',
        'grant',
        'handle',
        'has',
        'initialize',
        'is',
        'list',
        'merge',
        'mount',
        'multiply',
        'onChange',
        'onError',
        'parse',
        'preValidate',
        'register',
        'remove',
        'run',
        'save',
        'search',
        'send',
        'set',
        'sort',
        'split',
        'start',
        'strip',
        'subtract',
        'sum',
        'throw',
        'to',
        'transform',
        'update',
        'validate',
        'verify',
        'warn',
    ],
}
